/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/manufacturers/{manufacturer_id}/families": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manufacturer_id: number;
            };
            cookie?: never;
        };
        /** List families for a manufacturer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    manufacturer_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description families found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftFamily"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a family under a manufacturer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    manufacturer_id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AircraftFamilyInput"];
                };
            };
            responses: {
                /** @description family created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftFamily"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Retrieve a family */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description family found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftFamily"];
                    };
                };
                /** @description family not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a family */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AircraftFamilyInput"];
                };
            };
            responses: {
                /** @description family updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftFamily"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a family */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description family deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families/{family_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        /** List variants for a family */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    family_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description variants found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftVariant"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a variant under a family */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    family_id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AircraftVariantInput"];
                };
            };
            responses: {
                /** @description variant created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftVariant"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search variants */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filter by body type:
                     *      * `narrowbody`
                     *      * `widebody`
                     *      * `regional_jet`
                     *      * `biplane`
                     * @enum {unknown}
                     */
                    body_type?: string;
                    /**
                     * @description Filter by engine type
                     * @enum {unknown}
                     */
                    engine_type?: string;
                    /**
                     * @description Filter by range category
                     * @enum {unknown}
                     */
                    range_category?: string;
                    /** @description Minimum range in km */
                    min_range_km?: number;
                    /** @description Minimum passenger capacity */
                    max_passengers?: number;
                    /**
                     * @description Filter by status
                     * @enum {unknown}
                     */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description variants found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftVariant"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Retrieve a variant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description variant found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftVariant"];
                    };
                };
                /** @description variant not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a variant */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AircraftVariantInput"];
                };
            };
            responses: {
                /** @description variant updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftVariant"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a variant */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description variant deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{id}/discontinue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discontinue a variant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description variant discontinued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AircraftVariant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{id}/operators": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** List airlines operating this variant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description operators found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Airline"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List airlines */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by country */
                    country?: string;
                    /** @description Filter by IATA code */
                    iata_code?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description airlines found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Airline"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an airline */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AirlineInput"];
                };
            };
            responses: {
                /** @description airline created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Airline"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Retrieve an airline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description airline found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Airline"];
                    };
                };
                /** @description airline not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update an airline */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AirlineInput"];
                };
            };
            responses: {
                /** @description airline updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Airline"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an airline */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description airline deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines/{id}/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** List fleet entries for an airline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description fleet entries found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FleetEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines/{airline_id}/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airline_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a variant to fleet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    airline_id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FleetEntryInput"];
                };
            };
            responses: {
                /** @description fleet entry created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FleetEntry"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines/{airline_id}/fleet/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airline_id: number;
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a fleet entry */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    airline_id: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FleetEntryInput"];
                };
            };
            responses: {
                /** @description fleet entry updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FleetEntry"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        post?: never;
        /** Remove a fleet entry */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    airline_id: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description fleet entry deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines/{airline_id}/fleet/{id}/phase-out": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airline_id: number;
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Phase out a fleet entry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    airline_id: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description fleet entry phased out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FleetEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manufacturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List manufacturers */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by country */
                    country?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description manufacturers found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manufacturer"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a manufacturer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ManufacturerInput"];
                };
            };
            responses: {
                /** @description manufacturer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manufacturer"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manufacturers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Retrieve a manufacturer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description manufacturer found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manufacturer"];
                    };
                };
                /** @description manufacturer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a manufacturer */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ManufacturerInput"];
                };
            };
            responses: {
                /** @description manufacturer updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Manufacturer"];
                    };
                };
                /** @description invalid request */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Errors"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a manufacturer */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description manufacturer deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Manufacturer: {
            id: number;
            name: string;
            country: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ManufacturerInput: {
            manufacturer: {
                name: string;
                country: string;
            };
        };
        AircraftFamily: {
            id: number;
            name: string;
            manufacturer_id: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AircraftFamilyInput: {
            aircraft_family: {
                name: string;
            };
        };
        AircraftVariant: {
            id: number;
            aircraft_family_id: number;
            name: string;
            iata_code: string;
            /** @enum {string} */
            engine_type: "turbofan" | "turboprop" | "piston" | "propeller";
            /** @enum {string} */
            body_type: "narrowbody" | "widebody" | "regional_jet" | "biplane";
            /** @enum {string} */
            range_category: "short" | "medium" | "long";
            range_km: number;
            max_passengers: number;
            /** Format: float */
            max_cargo_tonnes?: number | null;
            /** Format: date */
            entry_into_service?: string | null;
            /** @enum {string} */
            status: "active" | "discontinued" | "in_development";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AircraftVariantInput: {
            aircraft_variant: {
                name: string;
                iata_code: string;
                /** @enum {string} */
                engine_type: "turbofan" | "turboprop" | "piston" | "propeller";
                /** @enum {string} */
                body_type: "narrowbody" | "widebody" | "regional_jet" | "biplane";
                /** @enum {string} */
                range_category: "short" | "medium" | "long";
                range_km: number;
                max_passengers: number;
                /** Format: float */
                max_cargo_tonnes?: number;
                /** Format: date */
                entry_into_service?: string;
                /** @enum {string} */
                status: "active" | "discontinued" | "in_development";
            };
        };
        Airline: {
            id: number;
            name: string;
            iata_code: string;
            country: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AirlineInput: {
            airline: {
                name: string;
                iata_code: string;
                country: string;
            };
        };
        FleetEntry: {
            id: number;
            airline_id: number;
            aircraft_variant_id: number;
            fleet_count: number;
            /** Format: float */
            avg_age_years?: number | null;
            /** @enum {string} */
            status: "active" | "phasing_out" | "ordered";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FleetEntryInput: {
            fleet_entry: {
                aircraft_variant_id: number;
                fleet_count: number;
                /** Format: float */
                avg_age_years?: number;
                /** @enum {string} */
                status: "active" | "phasing_out" | "ordered";
            };
        };
        Errors: {
            errors?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
